### ISSUE TITLE
Scaffold-DbContext remoting error

### ISSUE THREAD

**Issue by kerncarboni** [alexwiese/EntityFrameworkCore.OpenEdge#9]
Managed to get the scaffold-dbcontext to work once successfully. Not sure what happened after that with a VS2019 update but this is the current error we receive while trying to scaffold an old Progress 10.2B SP8 for a client.
Currently limited into using 32bit odbc driver (Progress OpenEdge 10.2B 5.30.00.109) with .net 4.72 due to current installation. Unfortunately limited Progress knowledge within the team so any help appreciated.

PM> Scaffold-DbContext "dsn=CCCTEST1; password=;" EntityFrameworkCore.OpenEdge -Context CedarContext -OutPutDir Models -verbose
Using project 'Affco.Domain.Db.Cedar.Scaffold'.
Using startup project 'Affco.Domain.Db.Cedar.Scaffold'.
Build started...
Build succeeded.
C:\Users\kyc\.nuget\packages\microsoft.entityframeworkcore.tools\2.1.4\tools\net461\win-x86\ef.exe dbcontext scaffold "dsn=CCCTEST1; password=;" EntityFrameworkCore.OpenEdge --json --output-dir Models --context CedarContext --verbose --no-color --prefix-output --assembly C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold\bin\Debug\Affco.Domain.Db.Cedar.Scaffold.exe --startup-assembly C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold\bin\Debug\Affco.Domain.Db.Cedar.Scaffold.exe --project-dir C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold\ --language C# --working-dir C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar --root-namespace Affco.Domain.Db.Cedar.Scaffold
Using assembly 'Affco.Domain.Db.Cedar.Scaffold'.
Using startup assembly 'Affco.Domain.Db.Cedar.Scaffold'.
Using application base 'C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold\bin\Debug'.
Using working directory 'C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold'.
Using root namespace 'Affco.Domain.Db.Cedar.Scaffold'.
Using project directory 'C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold\'.
Using configuration file 'C:\Source\Affco.Domain.Db\Affco.Domain.Db.Cedar\Affco.Domain.Db.Cedar.Scaffold\bin\Debug\Affco.Domain.Db.Cedar.Scaffold.exe.config'.
Finding design-time services for provider 'EntityFrameworkCore.OpenEdge'...
Using design-time services from provider 'EntityFrameworkCore.OpenEdge'.
Finding design-time services referenced by assembly 'Affco.Domain.Db.Cedar.Scaffold'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'Affco.Domain.Db.Cedar.Scaffold'...
No design-time services were found.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Remoting.RemotingException: Cannot load type 'Microsoft.EntityFrameworkCore.Design.IOperationResultHandler, Microsoft.EntityFrameworkCore.Design, Version=2.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Server stack trace: 
   at System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod(Boolean bThrowIfNotResolved)
   at System.Runtime.Remoting.Messaging.MethodCall..ctor(SmuggledMethodCallMessage smuggledMsg, ArrayList deserializedArgs)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.EntityFrameworkCore.Design.IOperationResultHandler.OnError(String type, String message, String stackTrace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute[T](Func`1 action)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext..ctor(OperationExecutor executor, Object resultHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor.Execute(String operationName, Object resultHandler, IDictionary arguments)
   at CallSite.Target(Closure , CallSite , OperationExecutorBase , String , Object , IDictionary )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperationImpl(String operationName, IDictionary arguments)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.ScaffoldContext(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.
PM>

**Comment by alexwiese** [comment]
That sounds like a conflict with a dependency version.
If you're using EF Core 2.1.4 please ensure you also have version 2.1.4 of the `Microsoft.EntityFrameworkCore.Tools` package. This is the package that has the scaffolding tools.
This is what my working packages.config looks like (using EF Core 2.1.11):

```<packages>
  <package id="EntityFrameworkCore.OpenEdge" version="1.0.7" targetFramework="net472" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore" version="2.1.11" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Abstractions" version="2.1.11" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Analyzers" version="2.1.11" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Design" version="2.1.11" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="2.1.11" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Tools" version="2.1.11" targetFramework="net472" developmentDependency="true" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Caching.Memory" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.DependencyInjection" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net472" />
  <package id="Remotion.Linq" version="2.2.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net472" />
  <package id="System.Collections.Immutable" version="1.5.0" targetFramework="net472" />
  <package id="System.ComponentModel.Annotations" version="4.5.0" targetFramework="net472" />
  <package id="System.Data.Odbc" version="4.5.0" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.5.1" targetFramework="net472" />
  <package id="System.Interactive.Async" version="3.2.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.1" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.1" targetFramework="net472" />
</packages>```

And the binding redirects look like so:
```    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ComponentModel.Annotations" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.EntityFrameworkCore" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.11.0" newVersion="2.1.11.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.EntityFrameworkCore.Relational" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.11.0" newVersion="2.1.11.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.1" newVersion="4.0.3.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Caching.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.EntityFrameworkCore.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.6.0" newVersion="2.1.11.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Caching.Memory" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Logging" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>```

After installing the correct versions of the packages please restart VS to ensure it uses the latest version of the tools in the *Package Manager Console*.

You mention  that you don't have a lot of OpenEdge experience, there are some gotchas with OpenEdge:
For example, after scaffolding, you may have strange behaviour if you don't set primary keys correctly. OpenEdge doesn't have a requirement for unique primary keys/indexes. So it's possible to have a primary index configured that is _not_ unique. EF Core will not handle this well as it uses the primary key to compare the entity objects, so it will effectively "merge" any records with the same "primary key". OpenEdge has a "hidden" field called `rowid` which you can use as a primary key if you need to (in the scenario where your DB has no proper primary key(s)). Example of using `rowid` as the primary key:

```[Key]
        [Column("rowid")]
        public string Rowid { get; set; }```

**Comment by kerncarboni** [comment]
Created a quick new project in VS2017 and installed 2.1.11 packages.
Still get the same error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Remoting.RemotingException: Cannot load type 'Microsoft.EntityFrameworkCore.Design.IOperationResultHandler, Microsoft.EntityFrameworkCore.Design, Version=2.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Server stack trace: 
   at System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod(Boolean bThrowIfNotResolved)
   at System.Runtime.Remoting.Messaging.MethodCall..ctor(SmuggledMethodCallMessage smuggledMsg, ArrayList deserializedArgs)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.EntityFrameworkCore.Design.IOperationResultHandler.OnError(String type, String message, String stackTrace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute[T](Func`1 action)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext..ctor(OperationExecutor executor, Object resultHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor.Execute(String operationName, Object resultHandler, IDictionary arguments)
   at CallSite.Target(Closure , CallSite , OperationExecutorBase , String , Object , IDictionary )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperationImpl(String operationName, IDictionary arguments)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.ScaffoldContext(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

I have been given this info regarding Progess settings and ran scaffold against all ports?
psc-writ-odbc           3946/tcp                      # CCC PSC TEST ODBC ON PS-WRI01
psc-writ-sql            3947/tcp                         # CCC PSC TEST SQL ON PS-WRI01
psc-wri-testSite  3948/tcp                             # CCC PSC WRI Test ON PS-WRI01

I also enabled ODBC logging and there seems to be data being returned from Progress as recognizable fieldnames are appearing in the log. The PMC runs for approx 5 minutes then eventually bombs out.

ConsoleApp1 --r 35ec-1a00	EXIT  SQLGetData  with return code 0 (SQL_SUCCESS)
		HSTMT               0x0199E7C8
		UWORD                        1 
		SWORD                       -8 <SQL_C_WCHAR>
		PTR                 0x0147D000 [      26] "AHFaultAction"
		SQLLEN                  4094
		SQLLEN *            0x0133CD54 (26)

ConsoleApp1 --r 35ec-1a00	ENTER SQLFetch 
		HSTMT               0x0199E7C8

ConsoleApp1 --r 35ec-1a00	EXIT  SQLFetch  with return code 0 (SQL_SUCCESS)
		HSTMT               0x0199E7C8

ConsoleApp1 --r 35ec-1a00	ENTER SQLGetData 
		HSTMT               0x0199E7C8
		UWORD                        1 
		SWORD                       -8 <SQL_C_WCHAR>
		PTR                 0x0147D000 
		SQLLEN                  4094
		SQLLEN *            0x0133CD54

ConsoleApp1 --r 35ec-1a00	EXIT  SQLGetData  with return code 0 (SQL_SUCCESS)
		HSTMT               0x0199E7C8
		UWORD                        1 
		SWORD                       -8 <SQL_C_WCHAR>
		PTR                 0x0147D000 [      20] "AHLocation"
		SQLLEN                  4094
		SQLLEN *            0x0133CD54 (20)

**Comment by alexwiese** [comment]
For what it's worth I'm running against OE 11.7.3 - hopefully it's not a 10.x compat problem.
But I'm still thinking with that error it's an issue with the EF Core Tools package that it's attempting to load.  Check to make sure that in your csproj file there should be a line that imports the EF Core Design time tools.

```<Import Project="..\packages\Microsoft.EntityFrameworkCore.Design.2.1.11\build\net461\Microsoft.EntityFrameworkCore.Design.props" Condition="Exists('..\packages\Microsoft.EntityFrameworkCore.Design.2.1.11\build\net461\Microsoft.EntityFrameworkCore.Design.props')" />
```

This is the SQL that's run against the database to get the schema information to do the scaffolding.
You could try running this SQL and seeing if you get valid output.

```SELECT
  "_Field-Name",
  "_Data-Type",
  "_File-Name" as name,
  "_Prime-Index" as primeindex,
  "_Mandatory",
  "_index-recid" as identity,
  "_initial"
FROM
  pub. "_field" f
  INNER JOIN pub. "_File" t ON t.rowid = f."_File-recid"
  LEFT JOIN pub. "_index-field" if ON if."_index-recid" = t."_Prime-Index"
  AND if."_field-recid" = f.rowid
ORDER BY
  f."_Order"
```

The data it loads should include all of the fields, for all of the tables, the data type, primary index id, mandatory, identity index id, and default/initial value of the field. If this data won't load then that could cause an issue.

Another thing you can try is scaffolding against a ["sports2000" database](https://knowledgebase.progress.com/articles/Article/000036167) just to rule out the issue being caused by a quirk in your database schema.

I've also attached a ZIP with my working Solu
[OEEFTest.zip](https://github.com/alexwiese/EntityFrameworkCore.OpenEdge/files/3429911/OEEFTest.zip)

tion/Project. You should be able to just open it up and run the Scaffold-DbContext command with your DB connection string.

**Comment by kerncarboni** [comment]
Hi Alex;

Thanks for project. Came up with same error when I ran it....but ran
perfectly on another machine and generated entire schema so we're hopefully
back on track. Must be my machine...possibly last VS upgrade or one of the
multiple progress odbc installations I've been trialling. Thanks for the
help...and the nuget package. Been a lifesaver using entity framework with
progress.

Cheers
Kern

**Comment by alexwiese** [comment]
Thanks Kern. Appreciate it.
I understand how frustrating it can be working with a Progress database 😊
